version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache
      - ./:/app
    ports:
      - '8000:80'
    depends_on:
      -  db
  db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: example
